# Generated by Django 4.0.3 on 2022-05-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=3, upload_to='myimages'),
            preserve_default=False,
        ),
    ]
